routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\OpdController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\EvaluasiController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\PeriodikController;
use App\Http\Controllers\SubkategoriController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::middleware('auth')->group(function() {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::resource('periodik',PeriodikController::class);

    Route::resource('opd',OpdController::class);

    Route::resource('kategori',KategoriController::class);

    Route::resource('sub_kategori',SubkategoriController::class);

    Route::resource('user',UserController::class);
    Route::put('user/reset-password/{id}', [UserController::class, 'updatePassword'])->name('user.password');

    Route::resource('evaluasi',EvaluasiController::class)->except(['show']);
    Route::get('/evaluasi/getSubKategori', [EvaluasiController::class, 'getSubKategori'])->name('evaluasi.getSubKategori');
    Route::get('/evaluasi/print/{evaluasi_id}', [EvaluasiController::class, 'printPDF'])->name('evaluasi.print');

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/SubKategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SubKategori extends Model
{
    use HasFactory;

    protected $table = 'sub_kategori';

    protected $fillable = [
        'nama',
        'kategori_id',
        'status_tampil'
    ];

    public function kategori()
    {
        return $this->belongsTo(Kategori::class);
    }

    public function detailEvaluasi()
    {
        return $this->hasOne(Detail::class);
    }


}

app/Http/Controllers/SubkategoriController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kategori;
use App\Models\SubKategori;
use Illuminate\Http\Request;

class SubkategoriController extends Controller
{
    public function index ()
    {
        $sub_kategori = SubKategori ::get();

        return view('Sub_kategori.index', ['sub_kategori' => $sub_kategori]);
    }
    public function create ()
    {
        $kategori = Kategori ::get();
        return view('Sub_kategori.create', ['kategori' => $kategori]  );
    }
    public function store (Request $request)
    {
        $validatedData = $request->validate([
            'nama' => 'required|unique:sub_kategori',
            'status_tampil' => 'required',
            'kategori_id' => 'required'
        ] , [
            'required' => ':attribute tidak boleh kosong',
            'unique' => ':attribute sudah dipakai'
        ], [
            'nama' => "Nama",
            'status_tampil' => "Status tampil",
            'kategori_id' => "Kategori"
        ]);
        SubKategori::create($validatedData);
        return redirect()->route('sub_kategori.index');
    }

    public function edit($id)
    {
        $sub_kategori=SubKategori::find($id);
        $kategori=Kategori::all();
        return view ('Sub_kategori.edit',
        [
            'sub_kategori' => $sub_kategori,
            'kategori' => $kategori
    ]);
    }

    public function update(Request $request,$id)
    {
        $sub_kategori = SubKategori::find($id);
        $validatedData = $request->validate([
            'nama' => 'required|unique:kategori|',
            'status_tampil' => 'required',
            'kategori_id' => 'required'
        ] , [
            'required' => ':attribute tidak boleh kosong',
            'unique' => ':attribute sudah dipakai'
        ], [
            'nama' => "Nama",
            'status_tampil' => "Status tampil",
            'kategori_id' => "Kategori"
        ]);
        $sub_kategori->update($validatedData);
        return redirect()->route('sub_kategori.index');
    }

    public function destroy($id)
    {
        
        $sub_kategori = SubKategori::find($id);
        $sub_kategori->delete();
        return redirect()->route('sub_kategori.index');
    }

    public function show ($id)
    {

    }
}

resources/views/Sub_kategori/create.blade.php
@extends('template.master')
@section('title', 'Tambah Sub Kategori')
@section('content')
    <form action="{{ route('sub_kategori.store') }}" method="post">
        @csrf
        <div class="row">
            <div class="col-12">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Tambah Sub Kategori</h6>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="nama">Nama Sub Kategori</label>
                            <input type="text" class="form-control @error('nama') is-invalid @enderror" id="nama"
                                name="nama">
                            @error('nama')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="kategori_id">Nama Kategori</label>
                            <select class="form-control @error('kategori_id') is-invalid @enderror"
                                id="kategori_id" name="kategori_id">
                                @foreach ($kategori as $row)
                                    <option value="{{ $row->id }}">{{ $row->nama }}</option>
                                @endforeach
                            </select>
                            @error('nama')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label>Status</label>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="status_tampil" id="aktif"
                                    value="1" checked>
                                <label class="form-check-label" for="aktif">
                                    Aktif
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="status_tampil" id="tidak_aktif"
                                    value="0">
                                <label class="form-check-label" for="tidak_aktif">
                                    Tidak Aktif
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

@endsection

resources/views/Sub_kategori/edit.blade.php
@extends('template.master')
@section('title', 'Edit Sub Kategori')
@section('content')
    <form action="{{ route('sub_kategori.update', $sub_kategori->id) }}" method="post">
      @csrf
      @method('put')
        <div class="row">
            <div class="col-12">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Tambah Sub Kategori</h6>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="nama">Nama Sub Kategori</label>
                            <input type="text" class="form-control @error('nama') is-invalid @enderror" id="nama"
                                name="nama" value={{ old('nama', $sub_kategori->nama) }}>
                            @error('nama')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                          <label for="kategori_id">Nama Kategori</label>
                          <select class="form-control @error('kategori_id') is-invalid @enderror" id="kategori_id"
                              name="kategori_id">
                              @foreach ($kategori as $row)
                              <option value="{{ $row->id }}">{{ $row->nama }}</option>
                              @endforeach
                            </select>
                          @error('nama')
                              <div class="invalid-feedback">
                                  {{ $message }}
                              </div>
                          @enderror
                      </div>
                        <div class="form-group">
                            <label>Status</label>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="status_tampil" id="aktif"
                                    value="1" @checked(old('status_tampil', $sub_kategori->status_tampil === 1))>
                                <label class="form-check-label" for="aktif">
                                    Aktif
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="status_tampil" id="tidak_aktif"
                                    value="0"@checked(old('status_tampil', $sub_kategori->status_tampil === 0))>
                                <label class="form-check-label" for="tidak_aktif">
                                    Tidak Aktif
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

@endsection

resources/views/Sub_kategori/index.blade.php
@extends('template.master')
@section('title','Sub Kategori')
@section('content')
     <!-- DataTales Example -->
     <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Data Sub Kategori</h6>
        </div>
        <div class="card-body">
            <a href="{{ route('sub_kategori.create') }}" class="btn btn-primary mb-3">Tambah Sub Kategori</a>
            <div class="table-responsive">
                <table id="datatable" class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama</th>
                            <th>Nama Kategori</th>
                            <th>Status Tampil</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($sub_kategori as $row )
                        <tr>
                            <th>{{ $loop->iteration }}</th>
                            <td>{{ $row->nama }}</td>
                            <td>{{ $row->kategori->nama}}</td>
                            <td>@if ($row->status_tampil)
                                Aktif
                            @else
                                Tidak Aktif
                            @endif
                            </td>

                            <td>
                                <a href="{{ route('sub_kategori.edit', $row->id) }}"class="btn btn-warning">Edit</a>
                                <form action="{{ route('sub_kategori.destroy', $row->id) }}" method="POST" style="display: inline-block;">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Anda yakin ingin menghapus data ini?')">Hapus</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('script')
<script>let table = new DataTable('#datatable');</script>
@endpush