routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\OpdController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\EvaluasiController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\PeriodikController;
use App\Http\Controllers\SubkategoriController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::middleware('auth')->group(function() {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::resource('periodik',PeriodikController::class);

    Route::resource('opd',OpdController::class);

    Route::resource('kategori',KategoriController::class);

    Route::resource('sub_kategori',SubkategoriController::class);

    Route::resource('user',UserController::class);
    Route::put('user/reset-password/{id}', [UserController::class, 'updatePassword'])->name('user.password');

    Route::resource('evaluasi',EvaluasiController::class)->except(['show']);
    Route::get('/evaluasi/getSubKategori', [EvaluasiController::class, 'getSubKategori'])->name('evaluasi.getSubKategori');
    Route::get('/evaluasi/print/{evaluasi_id}', [EvaluasiController::class, 'printPDF'])->name('evaluasi.print');

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/Kategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    use HasFactory;

    protected $table = 'kategori';

    protected $fillable = [
        'nama',
        'status_tampil',
        'jenis_sumber',
        'periodik_id'
    ];

    public function periodik()
    {
        return $this->belongsTo(Periodik::class);
    }

    public function sub_kategori()
    {
        return $this->hasMany(SubKategori::class);
    }
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kategori;
use App\Models\Periodik;
use Illuminate\Http\Request;

class KategoriController extends Controller
{
    public function index ()
    {
        $kategori = Kategori::get();

        return view('Kategori.index', ['kategori' => $kategori]);
    }

    public function create ()
    {
        return view ('Kategori.create');
    }

    public function store (Request $request)
    {
        $periodik_aktif = Periodik::where('is_aktif', 1)->first();
        $validatedData = $request->validate([
            'nama' => 'required|unique:kategori|',
            'status_tampil' => 'required',
            'jenis_sumber' => 'required',
        ] , [
            'required' => ':attribute tidak boleh kosong',
            'unique' => ':attribute sudah dipakai'
        ], [
            'nama' => "Nama",
            'status_tampil' => "Status tampil",
            'jenis_sumber' => "Jenis sumber",
        ]);
        $data = [
            'nama' => $validatedData['nama'],
            'status_tampil' => $validatedData['status_tampil'],
            'jenis_sumber' => $validatedData['jenis_sumber'],
            'periodik_id' => $periodik_aktif->id
        ];
        Kategori::create($data);
        return redirect()->route('kategori.index');
    }
    public function edit($id)
    {
        $kategori=Kategori::find($id);
        // dd($kategori)->all();
        return view ('Kategori.edit', ['kategori' => $kategori]);
    }

    public function update(Request $request,$id)
    {
        $kategori = Kategori::find($id);
        $validatedData = $request->validate([
            'nama' => 'required|unique:kategori,nama,' . $id,
            'status_tampil' => 'required',
            'jenis_sumber' => 'required',
        ] , [
            'required' => ':attribute tidak boleh kosong',
            'unique' => ':attribute sudah dipakai'
        ], [
            'nama' => "Nama",
            'status_tampil' => "Status tampil",
            'jenis_sumber' => "Jenis sumber",
        ]);
        $kategori->update($validatedData);
        return redirect()->route('kategori.index');
    }

    public function destroy($id)
    {
        $kategori = Kategori::find($id);
        $kategori->delete();
        return redirect()->route('kategori.index');
    }

}

resources/views/Kategori/create.blade.php
@extends('template.master')
@section('title', 'Form Kategori')
@section('content')
    <form action="{{ route('kategori.store') }}" method="post">
        @csrf
        <div class="row">
            <div class="col-12">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Form Tambah Kategori</h6>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="nama">Nama Kategori</label>
                            <input type="text" class="form-control @error('nama') is-invalid @enderror" id="nama"
                                name="nama" required>
                            @error('nama')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label>Status</label>
                            <div class="form-check">
                                <input class="form-check-input " type="radio" name="status_tampil" id="aktif"
                                    value="1" checked>
                                <label class="form-check-label" for="aktif">
                                    Aktif
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="status_tampil" id="tidak_aktif"
                                    value="0">
                                <label class="form-check-label" for="tidak_aktif">
                                    Tidak Aktif
                                </label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="jenis_sumber">Jenis Sumber</label>
                            <select class="form-control @error('jenis_sumber') is-invalid @enderror" id="jenis_sumber"
                                name="jenis_sumber" required>
                               <option value="utama">Fitur Utama</option>
                               <option value="rekomendasi">Fitur Rekomendasi</option>
                            </select>
                            @error('jenis_sumber')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

@endsection

resources/views/Kategori/edit.blade.php
@extends('template.master')
@section('title', 'Form Kategori')
@section('content')
    <form action="{{ route('kategori.update', $kategori->id) }}" method="post">
        @csrf
        @method('put')
        <div class="row">
            <div class="col-12">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Form Tambah Kategori</h6>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="nama">Nama Kategori</label>
                            <input type="text" class="form-control @error('nama') is-invalid @enderror" id="nama"
                                name="nama" value={{ old('nama', $kategori->nama) }}>
                            @error('nama')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label>Status</label>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="status_tampil" id="aktif"
                                    value="1" @checked(old('status_tampil', $kategori->status_tampil === 1))>
                                <label class="form-check-label" for="aktif">
                                    Aktif
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="status_tampil" id="tidak_aktif"
                                    value="0" @checked(old('status_tampil', $kategori->status_tampil === 0))>
                                <label class="form-check-label" for="tidak_aktif">
                                    Tidak Aktif
                                </label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="jenis_sumber">Jenis Sumber</label>
                            <input type="text" class="form-control @error('nama') is-invalid @enderror" id="jenis_sumber"
                                name="jenis_sumber" value={{ old('jenis_sumber', $kategori->jenis_sumber) }}">
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

@endsection

resources/views/Kategori/index.blade.php
@extends('template.master')
@section('title','Kategori')
@section('content')
     <!-- DataTales Kategori -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Data Kategori</h6>
        </div>
        <div class="card-body">
            <a href="{{ route('kategori.create') }}" class="btn btn-primary mb-3">Tambah Kategori</a>
            <div class="table-responsive">
                <table id="myTable" class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama</th>
                            <th>Periode</th>
                            <th>Status Tampil</th>
                            <th>Jenis Sumber</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($kategori as $row )
                        <tr>
                            <th>{{ $loop->iteration }}</th>
                            <td>{{ $row->nama }}</td>
                            <td>{{ $row->periodik_id }}</td>
                            <td>@if ($row->status_tampil)
                                Aktif
                            @else
                                Tidak Aktif
                            @endif
                            </td>
                            <td>{{ $row->jenis_sumber }}</td>
                            <td>
                                <a href="{{ route('kategori.edit', $row->id) }}"class="btn btn-warning">Edit</a>
                                <form action="{{ route('kategori.destroy', $row->id) }}" method="POST" style="display: inline-block;">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Anda yakin ingin menghapus data ini?')">Hapus</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('script')
<script>let table = new DataTable('#myTable');</script>
@endpush