routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\OpdController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\EvaluasiController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\PeriodikController;
use App\Http\Controllers\SubkategoriController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::middleware('auth')->group(function() {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::resource('periodik',PeriodikController::class);

    Route::resource('opd',OpdController::class);

    Route::resource('kategori',KategoriController::class);

    Route::resource('sub_kategori',SubkategoriController::class);

    Route::resource('user',UserController::class);
    Route::put('user/reset-password/{id}', [UserController::class, 'updatePassword'])->name('user.password');

    Route::resource('evaluasi',EvaluasiController::class)->except(['show']);
    Route::get('/evaluasi/getSubKategori', [EvaluasiController::class, 'getSubKategori'])->name('evaluasi.getSubKategori');
    Route::get('/evaluasi/print/{evaluasi_id}', [EvaluasiController::class, 'printPDF'])->name('evaluasi.print');

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/Periodik.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Periodik extends Model
{
    use HasFactory;
    protected $table = 'periodik';

    protected $fillable = ['nama', 'mulai', 'selesai', 'is_aktif'];

    protected $dates = ['mulai', 'selesai'];

    public function scopeAktif($query)
    {
        return $query->where('is_aktif', true);
    }
}

app/Http/Controllers/PeriodikController.php
<?php

namespace App\Http\Controllers;

use App\Models\Periodik;
use Illuminate\Http\Request;

class PeriodikController extends Controller
{
   public function index()
    {
        $periodik = Periodik::get();

        return view('Periodik.index', ['periodik' => $periodik]);
    }
    public function create ()
    {
        return view ('Periodik.create');
    }
    public function store (Request $request)
    {
        $validateData = $request->validate([
            'nama' => 'required|unique:periodik|',
            'mulai' => 'required|date',
            'selesai' => 'required|date|after:mulai',
            'is_aktif' => 'required'
        ] , [
            'required' => ':attribute tidak boleh kosong',
            'unique' => ':attribute sudah dipakai',
            'date' => ':attribute harus berupa tanggal',
            'after' => ':attribute harus sesudah :date'
        ] , [
            'nama' => 'Nama',
            'mulai' => 'Mulai',
            'selesai' => 'Selesai',
        ]);
        Periodik::create($validateData);
        return redirect()->route('periodik.index');
    }
    public function edit($id)
    {
        $periodik=Periodik::find($id);
        // dd($periodik)->all();
        return view ('periodik.edit', ['data' => $periodik]);
    }

    public function update(Request $request,$id)
    {
        $periodik = Periodik::find($id);
        $validateData = $request->validate([
            'nama' => 'required|unique:periodik,nama,' . $id,
            'mulai' => 'required|date',
            'selesai' => 'required|date|after:mulai',
            'is_aktif' => 'required'
        ] , [
            'required' => ':attribute tidak boleh kosong',
            'unique' => ':attribute sudah dipakai',
            'date' => ':attribute harus berupa tanggal',
            'after' => ':attribute harus sesudah :date'
        ] , [
            'nama' => 'Nama',
            'mulai' => 'Mulai',
            'selesai' => 'Selesai',
        ]);
        $periodik->update($validateData);
        return redirect()->route('periodik.index');
    }
    public function destroy($id)
    {
        $periodik = Periodik::find($id);
        $periodik->delete();
        return redirect()->route('periodik.index');
    }
}

resources/views/Periodik/create.blade.php
@extends('template.master')
@section('title', 'Form Periodik')
@section('content')
    <form action="{{ route('periodik.store') }}" method="post">
        @csrf
        <div class="row">
            <div class="col-12">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Form Tambah Periode</h6>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="nama">Nama Periode</label>
                            <input type="text" class="form-control @error('nama') is-invalid @enderror" id="nama"
                                name="nama" value={{ old('nama') }}>
                            @error('nama')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="mulai">Mulai</label>
                            <input type="date" class="form-control @error('mulai') is-invalid @enderror" id="mulai"
                                name="mulai" value={{ old('mulai') }}>
                            @error('mulai')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="selesai">Selesai</label>
                            <input type="date" class="form-control @error('selesai') is-invalid @enderror" id="selesai"
                                name="selesai" value={{ old('selesai') }}>
                            @error('selesai')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label>Status</label>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="is_aktif" id="aktif" value="1"
                                    checked>
                                <label class="form-check-label" for="aktif">
                                    Aktif
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="is_aktif" id="tidak_aktif"
                                    value="0">
                                <label class="form-check-label" for="tidak_aktif">
                                    Tidak Aktif
                                </label>
                            </div>
                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/Periodik/edit.blade.php
@extends('template.master')
@section('title', 'Form Periodik')
@section('content')
    <form action="{{ route('periodik.update', $data->id ) }}" method="post">
        @csrf
        @method('put')
        <div class="row">
            <div class="col-12">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Form Tambah Periode</h6>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="nama">Nama Periode</label>
                            <input type="text" class="form-control @error('nama') is-invalid @enderror" id="nama"
                                name="nama" value={{ old('nama', $data->nama) }}>
                            @error('nama')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="mulai">Mulai</label>
                            <input type="date" class="form-control @error('mulai') is-invalid @enderror" id="mulai"
                                name="mulai" value={{ old('mulai', $data->mulai) }}>
                            @error('mulai')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="selesai">Selesai</label>
                            <input type="date" class="form-control @error('selesai') is-invalid @enderror" id="selesai"
                                name="selesai" value={{ old('selesai', $data->selesai) }}>
                            @error('selesai')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label>Status</label>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="is_aktif" id="aktif"
                                value="1" @checked(old('is_aktif', $data->is_aktif === 1))>
                                <label class="form-check-label" for="aktif">
                                    Aktif
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="is_aktif" id="tidak_aktif"
                                    value="0" @checked(old('is_aktif', $data->is_aktif === 0))>
                                <label class="form-check-label" for="tidak_aktif">
                                    Tidak Aktif
                                </label>
                            </div>
                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/Periodik/index.blade.php
@extends('template.master')
@section('title', 'Periode')
@section('content')
    <!-- DataTales Kategori -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Data Periode</h6>
        </div>
        <div class="card-body">
            <a href="{{ route('periodik.create') }}" class="btn btn-primary mb-3">Tambah Periode</a>
            <div class="table-responsive">
                @if (session('success'))
                    <div class="alert alert-success">{{ session('success') }}</div>
                @endif
                <table id="datatable" class="datatable table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Periode</th>
                            <th>Mulai</th>
                            <th>Selesai</th>
                            <th>Status</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($periodik as $data)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $data->nama }}</td>
                                <td>{{ $data->mulai->format('d-m-Y') }}</td>
                                <td>{{ $data->selesai->format('d-m-Y') }}</td>
                                <td>{{ $data->is_aktif ? 'Aktif' : 'Tidak Aktif' }}</td>
                                <td>
                                    <a href="{{ route('periodik.edit', $data->id) }}" class="btn btn-warning btn-sm">Edit</a>
                                    <form action="{{ route('periodik.destroy', $data->id) }}" method="POST" style="display: inline-block;">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Anda yakin ingin menghapus data ini?')">Hapus</button>
                                    </form>
                                </td>

                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('script')
<script>let table = new DataTable('#datatable');</script>
@endpush